### ISSUE TITLE
어떤 일들을 해야할까요?

### ISSUE THREAD

**Issue by lalalalz** [IamLuckyguy/exchange#1]
어떤 것들을 차례대로 작업하면 좋을지 궁금합니다~

해당 내용 정하고 바로 작업하면 좋을 것 같습니다!

**Comment by lalalalz** [comment]
환율 서비스 제작 담당
- 한화를 입력하면, 여러 도시들의 환율된 정보를 실시간으로 출력
- 환율 정보 매일 11시에 게시 -> 매일 11시 05분에 스크립트 실행을 통해 데이터베이스에 환율 정보 저장
- 화면에서는 최초로 사이트 접속 시 해당 날짜의 환율 정보 불러오고, 해당 정보를 활용하여 환전 정보를 출력

**Comment by IamLuckyguy** [comment]
이걸 이제봤네요ㅋㅋ
11시 5분에 스케쥴러는 어떻게 실행할지 고민해보고 적용해보심 될듯요. 
@Scheduled 이거로도 구현 가능하지 싶은데 내가 신경을 못썼던게 서버 시간을 제대로 설정했는지 모르겠어요.
생각나는 좋은 방법 있으면 말해줘요.
