### ISSUE TITLE
feature/UI-002

### ISSUE THREAD

**Issue by IamLuckyguy** [IamLuckyguy/exchange#15]
구글 애드센스 스크립트 추가, 테스트
<script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-1089551323467984"
     crossorigin="anonymous"></script>

**Comment by IamLuckyguy** [comment]
@lalalalz 진수님 이거 feature/UI-002 브랜치에 업로드해놨는데 지금 작업하는 곳에 머지좀 해주실래용?

**Comment by lalalalz** [comment]
머지 완료했습니다.~
